name: Trigger Dispatch
on:
  push:
    branches:
    - master
    - develop

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger dispatch event
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.STORAGE_TOKEN }}" \
          https://api.github.com/repos/sYrongK/core-repository/dispatches \
          -d '{"event_type":"build-trigger"}'
